### ISSUE TITLE
README describes libreswan::conn params incorrectly

### ISSUE THREAD

**Issue by westbywest** [spacedog/puppet-libreswan#4]
For this usage in a class declaring libreswan module to work:
```puppet
$conns = hiera('libreswan::conns')
create_resources('libreswan::conn', $conns)
```
I'd need to define the conn parameters in YAML like this, in contradiction to the README.
```yaml
libreswan::conns:
  snt:
    options:
      left: 10.11.11.1
      leftsubnet: 10.0.1.0/24
      leftnexthop: 172.16.55.66
      leftsourceip: 10.0.1.1
      right: 192.168.22.1
      rightsubnet: 10.0.2.0/24
      rightnexthop: 172.16.88.99
      rightsourceip: 10.0.2.1
      keyingtries: %forever
```
Also, the README is a bit misleading in that the class libreswan::init doesn't actually have params named 'conns' or 'secrets.'
